### ISSUE TITLE
How to set running in gpu mode in squirrel?

### ISSUE THREAD

**Issue by junmuzi** [alexanderrichard/squirrel#1]
\# pwd
$squirrel_root_dir/examples/cvpr2017
\# ./train.sh 
Maximum number of threads for CPU matrix operations: 1
Maximum number of threads for CPU matrix operations: 1

Seems it just run in cpu mode, could anyone help to tell me how to set it running in gpu mode? Thanks.

**Comment by alexanderrichard** [comment]
This message ("Maximum number of threads for CPU matrix operations: 1") is due to Intel MKL when determining how many parallel CPU threads to use. It will always be printed, no matter if a GPU is used or not.

If you want to be sure if a GPU is used, check in the log file (e.g. log/training.log) for something like "using 1 of n GPUs" (where n is the number of CUDA capable GPUs installed on the machine). If no GPU is used/found, there will also be a message in the log file stating that no GPU could be found.

**Comment by junmuzi** [comment]
@alexanderrichard , thanks a lot. I just want to use your models for my research. Could you provide your trained  well models for me(Seems training these models will take a long time)? thank you very much.

**Comment by alexanderrichard** [comment]
Training should not take too long (12-24 hours per split) but I can provide the models for you next week.

EDIT: Trained models for Breakfast are available, see README in examples/cvpr2017.
